In [23]:
import numpy as np
from scipy.optimize import fsolve
import scipy
import pandas as pd

## Data

In [24]:
df = pd.DataFrame({'time':time,
                  'Trial 1 NF I':T_1_NF_I,
                  'Trial 1 NF O':T_1_NF_O,
                  'Trial 2 NF I':T_2_NF_I,
                  'Trial 2 NF O':T_2_NF_O,
                    'Trial 3 NF I':T_3_NF_I,
                  'Trial 3 NF O':T_3_NF_O,
                  'Trial 1 F I':T_1_F_I,
                  'Trial 1 F O':T_1_F_O,
                  'Trial 2 F I':T_2_F_I,
                  'Trial 2 F O':T_2_F_O,
                  'Trial 3 F I':T_3_F_I,
                  'Trial 3 F O':T_3_F_O,})

time = [1,2,3,4,5,6,7,8,9,10] #in minutes
T_1_NF_inf = 23.9
T_1_NF_O = [47,39.9,41.0,47.9,56.6,55,60.5,51.8,50.6,60.0]
T_1_NF_I = [76.8,77.8,78,74,73,75,73,73.8,73.9,71]
T_2_NF_inf = 24.7
T_2_NF_O = [49.0,50.2,54.2,52.8,57.9,58.9,59.2,58.6,55.5,57.2]
T_2_NF_I = [76.7,77.7,74.5,74.2,73.7,72.6,72.0,71.3,70.7,70.7]
T_3_NF_inf = 24.5
T_3_NF_O = [48.5,51.6,51.0,56.6,53.0,57.1,50.1,57.2,48.3,59.3]
T_3_NF_I = [76.2,75.2,74.5,74.0,74.1,72.8,74,72.3,74,70.9]
T_1_F_inf = 24.2
T_1_F_O = [46.7,47.4,47.9,47.9,46.5,46.8,42.1,42.8,44.4,35.6]
T_1_F_I = [75.1,73.2,71.6,70.2,69,67.8,67.2,66.7,64.5,67.3]
#Trial 2 with Fan had very big varying outside temp
T_2_F_inf = 27.2
T_2_F_O = [44,30.2,43,38.4,42.2,36.3,39.6,38.4,46,30.9]
T_2_F_I = [76.3,77.7,75.0,71,70.9,72.5,69.0,68.3,65.3,68.1]
T_3_F_inf = 28.2
T_3_F_O = [28.6,29.5,31.0,30.6,33,30.6,30.7,33.2,30.7,35.5]
T_3_F_I = [82.1,80.0,78.6,77.6,71.6,75.1,73.5,74.0,68.5,69.1]

In [25]:
df

time  Trial 1 NF I  Trial 1 NF O  Trial 2 NF I  Trial 2 NF O  Trial 3 NF I  \
0     1          76.8          47.0          76.7          49.0          76.2   
1     2          77.8          39.9          77.7          50.2          75.2   
2     3          78.0          41.0          74.5          54.2          74.5   
3     4          74.0          47.9          74.2          52.8          74.0   
4     5          73.0          56.6          73.7          57.9          74.1   
5     6          75.0          55.0          72.6          58.9          72.8   
6     7          73.0          60.5          72.0          59.2          74.0   
7     8          73.8          51.8          71.3          58.6          72.3   
8     9          73.9          50.6          70.7          55.5          74.0   
9    10          71.0          60.0          70.7          57.2          70.9   

   Trial 3 NF O  Trial 1 F I  Trial 1 F O  Trial 2 F I  Trial 2 F O  \
0          48.5         75.1         46.7         76.3         44.0   
1          51.6         73.2         47.4         77.7         30.2   
2          51.0         71.6         47.9         75.0         43.0   
3          56.6         70.2         47.9         71.0         38.4   
4          53.0         69.0         46.5         70.9         42.2   
5          57.1         67.8         46.8         72.5         36.3   
6          50.1         67.2         42.1         69.0         39.6   
7          57.2         66.7         42.8         68.3         38.4   
8          48.3         64.5         44.4         65.3         46.0   
9          59.3         67.3         35.6         68.1         30.9   

   Trial 3 F I  Trial 3 F O  
0         82.1         28.6  
1         80.0         29.5  
2         78.6         31.0  
3         77.6         30.6  
4         71.6         33.0  
5         75.1         30.6  
6         73.5         30.7  
7         74.0         33.2  
8         68.5         30.7  
9         69.1         35.5

## Adiabatic Solved

#### Solves for m

In [33]:
T_inf_T = T_3_F_inf
T_I_T = T_3_F_I[9]
T_O_T = T_3_F_O[9]

#solve for m
def M_adiabatic(m):
    T_inf = T_inf_T
    T_b = T_I_T
    T = T_O_T
    d = 0.009525
    L = 0.1524
    x = 0.12192
    P = ((d/2)**2)*np.pi
    A_c = 7.1255 * 10**-5
    k = 398
    #m = ((h*P)/k*A_c)**(1/2)
    m_calc = ((np.cosh(m*(L-x)))/(np.cosh(m*L))) - ((T-T_inf)/(T_b-T_inf))
    return m_calc

m_calc = fsolve(M_adiabatic,4)
m_calc

array([16.62291243])

#### Solves for h from m

In [20]:
#solves for heat transfer coefficient
def H_adiabatic(h):
    T_inf = T_inf_T
    T_b = T_I_T
    T = T_O_T
    d = 0.009525
    L = 0.1524
    x = 0.12192
    P = ((d/2)**2)*np.pi
    A_c = 7.1255 * 10**-5
    k = 398
    h_calc = ((h*2*np.pi*(0.0093/2))/(398*A_c))**(1/2) - m_calc
    return h_calc

h_calc = fsolve(H_adiabatic,3)
h_calc

array([268.21300333])

In [22]:
h_NF = [25.48,34.26,27.77] #in order of the three trials
q_NF = [0.001898,0.002522,0.002053] #in order of the three trials as well
h_F = [183.1,454.6,268.2]
q_f = [0.01301,0.03129,0.01853]

#### Finds q using h

In [27]:
def q(h):
    d = 0.009525
    L = 0.1524
    T_inf = T_inf_T
    T_b = T_I_T
    T = T_O_T
    A_c = 7.1255 * 10**-5
    k = 398
    P = ((d/2)**2)*np.pi
    m = ((h*P)/(k*A_c))**(1/2)
    M = ((h*P*k*A_c)**(1/2))*(T_b-T_inf)
    q = M * (np.tanh(m*L))
    return q, m, M

q(h_calc)

(array([0.11850873]), array([0.82091961]), array([0.95218724]))

## With Wind

In [40]:
T_inf_TF = T_3_F_inf
T_O_TF = T_3_F_O[9]
T_I_TF = T_3_F_I[9]

def H_wind(h):
    T_inf = T_inf_TF
    T_b = T_I_TF
    T = T_O_TF
    d = 0.009525
    L = 0.1524
    x = 0.12192
    P = ((d/2)**2)*np.pi
    A_c = 7.1255 * 10**-5
    k = 398
    m = ((h*P)/(k*A_c))**(1/2)
    h_calc = (np.cosh(m*L) + (h/(m*k))*np.sinh(m*(L-x)))/(np.cosh(m*L)+(h/(m*k))*np.sinh(m*L)) - ((T-T_inf)/(T_b-T_inf))
    return h_calc

h_calc = fsolve(H_wind,10)
h_calc

array([68331.46799208])

## Heat Exchanger Calcs

In [45]:
#The lists below will go like this:
#trial number, flow rate, t_hot_in, t_hot_out, t_cold_in, t_cold_out
m_3 = [[1,3,70.5,51.5,12.2,27],[2,3,70.8,54.3,13.4,29.6],[3,3,72.2,54,13.4,28.6]]
m_2 = [[1,2,70.5,53.6,13,31],[2,2,71.8,55.8,14,32.8],[3,2,71,55.9,13.6,32.6]]
m_1 = [[1,1,70.5,51.5,13.7,32.2],[2,1,71.5,52,15,37.1],[3,1,66.3,52.5,14.7,33.9]]
m_4 = [[1,4,65,54.5,13.8,27.5],[2,4,71,55.9,13.4,28.8],[3,4,73,55.8,13.8,28]]
m_05 = [[1,0.5,65,48.4,14.7,40.6],[2,0.5,71,48.4,15.3,40.5],[3,0.5,66,41.5,16,41.6]]

def U_transfer(lst,A,lst_empty):
    rho = 1000 #kg/m^3
    m = (lst[0][1] * 0.001 * 1000)/60
    cp = 4184
    for i in range(len(lst)):
        t_h_i = lst[i][2]
        t_h_o = lst[i][3]
        t_c_i = lst[i][4]
        t_c_o = lst[i][5]
        t_i = t_h_i - t_c_o
        t_o = t_h_o - t_c_i
        lmtd = (t_i - t_o)/(np.log(t_i/t_o))
        U = (m*cp*(t_c_o-t_c_i))/(lmtd*A)
        lst_empty.append(U)
    return lst_empty

U_3 = []
U_2 = []
U_05 = []

U_transfer(m_3,2,U_3)
U_transfer(m_2,2,U_2)
U_transfer(m_05,2,U_05)


[15.67779828071635, 13.822798065955068, 17.890406624591364]

In [46]:
U_3

[37.42535711076293, 41.27959907370376, 37.78131334383664]

In [47]:
U_2

[31.342794389278755, 32.46316378079158, 32.86161702969652]

In [48]:
U_05

[15.67779828071635, 13.822798065955068, 17.890406624591364]